kind: ConfigMap
apiVersion: v1
metadata:
  name: wg-configmap
  namespace: default
data:
  wg0.conf: |	
    [Interface]
    Address = 10.0.0.1/24
    ListenPort = 51820
    PrivateKey = 6Lv4V0te8QOhVQpDWuQn5OxYnzfDFYecI/fNxDTLn38=
    PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
