apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: wg
      protocol: UDP
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.service.labels.app }}
